apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spring
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring
        tier: frontend
    spec:
      containers:
      - image: kindergarten-internal
        imagePullPolicy: Never
        name: kindergarten-internal
        resources: {}
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://spring-mysql-0.spring-mysql:3306/kindergarten?useSSL=false&useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf-8"
          - name: SPRING_DATASOURCE_USERNAME
            value: "hbstudent"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "p@ssword123"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: spring
  labels:
    app: spring
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring
    tier: frontend
  type: ClusterIP
status:
  loadBalancer: {}
