# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: spring
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: spring
    tier: mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  labels:
    app: spring
    readonly: "true"
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: spring
    tier: mysql
