---
- hosts: webserver

  vars:
    github: "https://github.com/vasKatevas/"


  tasks:
    - name: check if internal exists
      shell: "[ -d \"{{internal}}\" ] && cd {{internal}} && git restore ."

    - name: check if internal exists
      shell: "[ -d \"{{external}}\" ] && cd {{external}} && git restore ."
    
    - name: clone internal
      git:
        repo: "{{github}}{{internal}}"
        version: "main"
        clone: yes
        dest: "{{internal}}"
      changed_when: true


    - name: clone external
      git:
        repo: "{{github}}{{external}}"
        version: "master"
        clone: yes
        dest: "{{external}}"
      changed_when: true
