---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml


  tasks:

    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Install Java using Ansible
      become: true
      apt:
        name: "openjdk-11-jdk"
        state: present



    - include_role:
        name: geerlingguy.mysql

    - include_role:
        name: geerlingguy.pip

    - name: upgrade pip
      pip: 
        executable: pip3
        name: pip
        state: latest

