---

- hosts: all
  tasks:


    - name: stop gunicorn
      service:
        name: gunicorn
        state: stopped
      become: yes

    - name: run tests
      shell: "python3 manage.py test"
      args:
        chdir: "{{workdir}}{{external}}kindergartent"

    - name: start gunicorn
      service:
        name: gunicorn
        state: started
      become: yes
